SELECT * FROM MAS_USER WHERE USERCODE = '080T12920'
SELECT * FROM MAS_USER WHERE ID IN (SELECT userid FROM MAS_USERHIERARCHY WHERE ParentUserID = 2155)

--DELETE FROM MAS_USERHIERARCHY WHERE ParentUserID = 2155
--INSERT INTO Mas_UserHierarchy VALUES ('SUPV', 715, 2155, GETDATE(), 'Minh');
