--SELECT TOP 10 * FROM CTS_Result WHERE user_ID = 750 ORDER BY REC_TIME_STAMP DESC

SELECT TOP 1000 * FROM INVENTORY_LIST_ITEM WHERE  INVENTORY_LIST_ID IN (SELECT ID FROM INVENTORY_LIST WHERE OPEN_DATE  = '3May16'
AND CHAIN_ID IN (SELECT ID FROM CHAINS WHERE ORG_ID = 81)
)
AND ACTUAL <> 0

SELECT * FROM INVENTORY_LIST WHERE CHAIN_ID = 1697
SELECT * FROM CHAINS WHERE ORG_ID = 81