--SELECT * FROM WF_Design WHERE SCRIPT LIKE '%CCVNHDB%'
--SELECT * FROM sys.servers


SELECT TOP 10 * FROM WF_TASKHEAD ORDER BY UPDATEDATE DESC
--SELECT * FROM WF_TASKFORM
/*
UPDATE WF_TASKDETAIL 
SET SCRIPTsqllog = REPLACE (SCRIPTsqllog, 'CCVNDB','CCVNHDB')
 WHERE SCRIPTsqllog LIKE '%CCVNDB%'

UPDATE WF_DESIGN 
SET SCRIPT = REPLACE (SCRIPT, 'CCVNDB','CCVNHDB')
 WHERE SCRIPT LIKE '%CCVNDB%'

EXEC sp_addlinkedserver @server='CCVNREPORTING'
EXEC sp_addlinkedsrvlogin 'CCVNREPORTING', 'false', NULL, 'sa', 'sharepoint@admin'*/