DELETE FROM INVENTORY_LIST_ITEM 
WHERE INVENTORY_LIST_ID = 42402

insert into INVENTORY_LIST_ITEM(INVENTORY_LIST_ID,PRODUCT_ID
												,OPENING_STOCK,OPENING_STOCK_EA
												,REC_TIME_STAMP,REC_USER_CODE)
SELECT	42402,MPLI.PRODUCT_ID
						,t.CLOSING_STOCK
						,t.CLOSING_STOCK_EA
						,GETDATE(),'Job'
				FROM MDC_PROD_LIST_ITEMS MPLI
					LEFT join (SELECT	PRODUCT_ID,ACTUAL,ACTUAL_EA,
										ISNULL(OPENING_STOCK+RECEIVED+Returned-SALES-BREAKAGES,0)
											AS CLOSING_STOCK,
										ISNULL(OPENING_STOCK_EA+RECEIVED_EA+Returned_EA-SALES_EA-BREAKAGES_EA,0)
											AS CLOSING_STOCK_EA
								FROM INVENTORY_LIST_ITEM
								WHERE INVENTORY_LIST_ID = 42135) t ON T.PRODUCT_ID=MPLI.PRODUCT_ID
				WHERE MPLI.MDC_PRODUCT_LIST_ID=1731 AND VALID=1