UPDATE INVENTORY_LIST_ITEM SET Opening_stock = 728  WHERE INVENTORY_LIST_ID = 68613 AND PRODUCT_ID = 170 
SELECT * FROM INVENTORY_LIST_ITEM WHERE INVENTORY_LIST_ID = 68613 AND PRODUCT_ID = 170 

SELECT TOP 20 * FROM INVENTORY_LIST WHERE CHAIN_ID = 1731 ORDER BY REC_TIME_STAMP DESC



SELECT	64928,MPLI.PRODUCT_ID
						,t.CLOSING_STOCK
						,t.CLOSING_STOCK_EA
						,GETDATE(),'Job'
				FROM MDC_PROD_LIST_ITEMS MPLI
					LEFT join (SELECT	PRODUCT_ID,ACTUAL,ACTUAL_EA,
										ISNULL(ISNULL(OPENING_STOCK,0)+RECEIVED+Returned-SALES-BREAKAGES,0)
											AS CLOSING_STOCK,
										ISNULL(ISNULL(OPENING_STOCK_EA,0)+RECEIVED_EA+Returned_EA-SALES_EA-BREAKAGES_EA,0)
											AS CLOSING_STOCK_EA
								FROM INVENTORY_LIST_ITEM
								WHERE INVENTORY_LIST_ID = 68241 AND PRODUCT_ID = 170 ) t ON T.PRODUCT_ID=MPLI.PRODUCT_ID
				WHERE MPLI.MDC_PRODUCT_LIST_ID=1731 AND VALID=1 AND MPLI.PRODUCT_ID = 170 