SELECT * FROM PRODUCTS WHERE COde = 'REBATE01'
SELECT * FROM MDC_PROD_LIST_ITEMS WHERE PRODUCT_ID = 793

SELECT * FROM SapProduct WHERE ProductID = 'REBATE01'
SELECT * FROM sapSalesOrgProduct WHERE ProductID = 'REBATE01'