ALTER TABLE ORDER_LINES_PROMO ADD [LineID] [numeric](20, 0) NOT NULL DEFAULT 0, [FreeLineID] [numeric](20, 0) NOT NULL DEFAULT 0 ;
ALTER TABLE ORDER_LINES_PROMO ADD OwnProductID INT NULL, FreeProductID INT NULL ;
ALTER TABLE ORDER_LINES_PROMO
    DROP CONSTRAINT PK_ORDER_LINES_PROMO;
ALTER TABLE ORDER_LINES_PROMO
    ADD CONSTRAINT PK_ORDER_LINES_PROMO PRIMARY KEY (ORDER_NO, PROMO_ID, LineID, FreeLineID);